# Generated by Django 5.1.3 on 2024-11-18 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_child'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='age',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
